### ISSUE TITLE
Create test suite

### ISSUE THREAD

**Issue by vphantom** [vphantom/pyritephp#1]
I usually develop in [documentation, test, code] cycles, but time ran short for PyriteView.  Let's start with an analogy with what I do on the Node side:

- "make test" runs **Istanbul** which is a code coverage reporter.  It runs all my test scripts in find-like fashion and generates an HTML tree of pretty reports and some data files.

- Each test script depends on **Tape** for producing TAP output.

- For CLI usage, I pass TAP through **Faucet** to make it pretty.

- For Travis-CI, I don't.  Travis-CI is also configured to invoke **Coveralls** to send Coveralls.IO a copy of Istanbul's "lcov.info".

In PHP, PHPUnit is probably the closest, although not nearly as simple as Perl's Test::More and Node's Tape.  I'm tempted to do like [TestTAP](https://github.com/walf443/php-test-tap) and update my old `Test.inc` to offer a Test::More/Tape style API wrapped in [php-code-coverage](https://packagist.org/packages/phpunit/php-code-coverage).

- [x] Install Linux distribution package `php7.0-xdebug`.  This probably means `composer.json` adds its first dev requirement, for "xdebug ~2.5".

- [x] Install PHPUnit stable: `composer require --dev phpunit/phpunit ^6.0`

- [x] Create at least one test to confirm that reporting works, fine-tune `Makefile` for options I prefer.

- [x] Install PHP-Coveralls: `composer require --dev satooshi/php-coveralls` to convert/send PHPUnit's coverage report (which is in "Clover" format?) to Coveralls.IO.

- [x] Set up repo with Travis-CI:
```yml
language: php

php:
 - 5.6
 - 7.0

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - [php?] vendor/bin/coveralls -v
```
